companies:
  - company_name: abeja-geniac # ABEJA
    schedule:
      - date: "2024-02-15"
        assigned_gpu_num: 48
  - company_name: stockmark-geniac # Stockmark
    schedule:
      - date: "2024-02-15"
        assigned_gpu_num: 48
  - company_name: pfe-geniac # PFE
    schedule:
      - date: "2024-02-15"
        assigned_gpu_num: 50
  - company_name: turing-geniac # Turing
    schedule:
      - date: "2024-02-15"
        assigned_gpu_num: 4
      - date: "2024-06-15"
        assigned_gpu_num: 35
  - company_name: llm-jp-geniac # NII
    schedule:
      - date: "2024-02-15"
        assigned_gpu_num: 75
  - company_name: team1 # Matsuo LB No.1
    schedule:
      - date: "2024-04-15"
        assigned_gpu_num: 21
  - company_name: team2 # Matsuo LB No.2
    schedule:
      - date: "2024-04-15"
        assigned_gpu_num: 21
  - company_name: sakanaai-geniac # Sakana AI
    schedule:
      - date: "2024-06-15"
        assigned_gpu_num: 32

### production ### 
path_to_dashboard:
  entity: geniac-gpu
  project: gpu-dashboard