wandb_dir: "/tmp"
ignore_tag: xyz
testmode: false
# testmode: true

path_to_dashboard:
  entity: geniac-gpu
  # project: gpu-dashboard
  project: test-gpu-dashboard # for test
  # artifact_name: gpu-usage
  # artifact_name: test-gpu-usage # for test
  artifact_name: test2 # for test

companies:
  - company_name: stockmark-geniac # Stockmark
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 48
      # - date: "2024-02-19"  # for test
        # assigned_gpu_node: 40
  - company_name: abeja-geniac # ABEJA
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 48
  - company_name: pfe-geniac # PFE
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 50
  - company_name: turing-geniac # Turing
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 4
      - date: "2024-06-15"
        assigned_gpu_node: 35
  - company_name: nii-geniac # NII
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 75
  - company_name: team1 # Matsuo LB No.1
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 21
  - company_name: team2 # Matsuo LB No.2
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 21
  - company_name: sakanaai-geniac # Sakana AI
    schedule:
      - date: "2024-06-15"
        assigned_gpu_node: 32