testmode: false
ignore_tag: other_gpu
tag: latest
wandb_dir: /tmp

dataset:
  entity: geniac-gpu
  project: gpu-dashboard-dev
  artifact: version_20240227

dashboard:
  entity: geniac-gpu
  project: gpu-dashboard-dev
  artifact: version_20240227
  tag_for_latest: latest

companies:
  - company: abeja-stockmark # ABEJA
    teams:
      - abeja-geniac
      - stockmark-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 96
    ignore_projects:
      - 100b
  # - company: abeja-geniac # ABEJA
  #   teams:
  #     - abeja-geniac
  #   schedule:
  #     - date: "2024-02-15"
  #       assigned_gpu_node: 48
  - company: pfe-geniac # PFE
    teams:
      - pfe-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 50
  # - company: stockmark-geniac # Stockmark
  #   teams:
  #     - stockmark-geniac
  #   schedule:
  #     - date: "2024-02-15"
  #       assigned_gpu_node: 48
  #   ignore_projects:
  #     - 100b
  - company: turing-geniac # Turing
    teams:
      - turing-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 4
      - date: "2024-06-15"
        assigned_gpu_node: 35
  - company: nii-geniac # NII
    teams:
      - nii-geniac
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 75
  - company: weblab-geniac # Matsuo LB
    teams:
      - weblab-geniac1
      - weblab-geniac2
      - weblab-geniac3
      - weblab-geniac4
      - weblab-geniac5
      - weblab-geniac6
      - weblab-geniac7
      - weblab-geniac8
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 21
  - company: sakanaai-geniac # Sakana AI
    teams:
      - sakanaai-geniac
    schedule:
      - date: "2024-06-15"
        assigned_gpu_node: 32