testmode: false
ignore_tag: other_gpu
tag: latest
wandb_dir: /tmp

dataset-path:
  - entity: geniac-gpu
    project: gpu-dashboard-dev
    artifact: version_20240227

dashboard-path:
  - entity: geniac-gpu
    project: test-gpu-dashboard
    tag_for_latest: latest

companies:
  - company: abeja-geniac # ABEJA
    teams:
      - abeja-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 48
  - company: pfe-geniac # PFE
    teams:
      - pfe-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 50
  - company: stockmark-geniac # Stockmark
    teams:
      - stockmark-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 48
    ignore_projects:
      - 100b
  - company: turing-geniac # Turing
    teams:
      - turing-geniac
    schedule:
      - date: "2024-02-15"
        assigned_gpu_node: 4
      - date: "2024-06-15"
        assigned_gpu_node: 35
  - company: nii-geniac # NII
    teams:
      - nii-geniac
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 75
  - company: weblab-geniac # Matsuo LB
    teams:
      - weblab-team1
      - weblab-team2
      - weblab-team3
      - weblab-team4
      - weblab-team5
      - weblab-team6
      - weblab-team7
      - weblab-team8
    schedule:
      - date: "2024-04-15"
        assigned_gpu_node: 21
  - company: sakanaai-geniac # Sakana AI
    teams:
      - sakanaai-geniac
    schedule:
      - date: "2024-06-15"
        assigned_gpu_node: 32